# Generated by Django 5.0.14 on 2025-05-28 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_comment_name_alter_customtag_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customtag',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='name'),
        ),
    ]
